config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  get 'static_pages/about'

  get '/about', to: 'static_pages#about', as: 'about'
  

  resources :entries

end

app/models/entry.rb
class Entry < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  def index
  	@entries = Entry.all
  end

  def show
  	@entry = Entry.find(params[:id])
  end

  def new
  	@entry = Entry.new
  end

  def create
  	if Entry.create(entry_params)
  		redirect_to entries_path
  	else
  		render :new
  	end
  end

  def edit
  	@entry = Entry.find(params[:id])
  end

  def update
    @entry = Entry.find(params[:id])
    if @entry.update(entry_params)
      redirect_to entries_path
    else
      render :edit
    end
  end

  private

  def entry_params
  	params.require(:entry).permit(:title, :body)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/entries/edit.html.erb
<h1>Edit Posts</h1>
<!-- rails uses the id or absence of id to know if it should be post or put -->
<%= form_for @entry do |f| %>
	<%= f.label :title %>
	<%= f.text_field :title %>
	<%= f.label :body %>
	<%= f.text_area :body %>
	<%= f.submit %>
<% end %>

app/views/entries/index.html.erb
<h1>POSTS</h1>
<p><%= link_to 'Create new post', new_entry_path %></p>
<% @entries.each do |entry| %>
	<h2><%= entry.title %></h2>
	<p><%= entry.body %></p>
	<%= link_to 'Show Entry', entry_path(entry) %>
	<%= link_to 'Edit', edit_entry_path(entry) %>
<% end %>

app/views/entries/new.html.erb
<h1>Add a New Post</h1>

<%= form_for @entry do |f| %>
	<%= f.label :title %>
	<%= f.text_field :title %>
	<%= f.label :body %>
	<%= f.text_area :body %>
	<%= f.submit %>
<% end %>

app/views/entries/show.html.erb
<h1><%= @entry.title %></h1>
<p><%= @entry.body %></p>

<%= link_to 'See all entries', entries_path %>

app/views/layouts/_navbar.html.erb
<%= link_to 'Home', root_path %> |
<%= link_to 'About', about_path %> |
<%= link_to 'Posts', entries_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BlogPost</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/navbar' %>
<%= yield %>

</body>
</html>

app/views/static_pages/about.html.erb
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/home.html.erb
<h1>Home Page</h1>